---
- name: Install required packages in Debian based distro
  become: yes
  apt:
    pkg:
      - sssd-ad
      - sssd-tools
      - realmd
      - adcli
      - dnsutils # some arm-based system need this