---
- name: Install required packages in Ubuntu
  become: true
  apt:
    pkg:
      - sssd-ad
      - sssd-tools
      - realmd
      - adcli
      - dnsutils # some arm-based system need this
  when: ansible_distribution == "Ubuntu"

- name: Install required packages in Debian
  become: true
  apt:
    pkg:
      - packagekit
      - realmd
      - adcli
      - sssd
      - sssd-ad
      - sssd-tools
      - libnss-sss
      - libpam-sss
    when: ansible_distribution == "Debian"
