---
- name: Discover ad domain
  command: realm discover "{{ domain_name }}"
  changed_when: false

- name: Join the Active Directory domain
  become: yes
  ansible.builtin.shell:
    cmd: echo "{{ domain_admin_password }}" | realm join --user {{ domain_admin_user }} --os-name {{ ansible_distribution }} --os-version {{ ansible_distribution_version }} {{ domain_name }}
  when: computer_name is not defined or not computer_name

- name: "Join the Active Directory domain as {{ computer_name }}"
  become: yes
  ansible.builtin.shell:
    cmd: echo "{{ domain_admin_password }}" |  realm join --computer-name {{ computer_name }} --user {{ domain_admin_user }} --os-name {{ ansible_distribution }} --os-version {{ ansible_distribution_version }} {{ domain_name }}
  when: computer_name is defined and computer_name