---
- name: Discover ad domain
  command: realm discover "{{ domain_name }}"
  changed_when: false

- name: Join the Active Directory domain
  become: yes
  expect:
    command: "realm join --user {{ domain_admin_user }} --os-name {{ ansible_distribution }} --os-version {{ ansible_distribution_version }} {{ domain_name }}"
    responses:
      Password for *: "{{ domain_admin_password }}"
  when: computer_name is not defined or not computer_name

- name: "Join the Active Directory domain as {{ computer_name }}"
  become: yes
  expect:
    command: "realm join --computer-name {{ computer_name }} --user {{ domain_admin_user }} --os-name {{ ansible_distribution }} --os-version {{ ansible_distribution_version }} {{ domain_name }}"
    responses:
      Password for *: "{{ domain_admin_password }}"
  when: computer_name is defined and computer_name