---
- name: Add sudoers for active directory groups
  become: true
  template:
    src: "{{ template_sudoers }}"
    dest: "{{ sudoers_path }}/00-ad-{{ domain_name | replace('.', '-')}}"
    validate: visudo -cf %s
  when: (domain_sudoers | default([], true)) | length
