---
# handlers file for join_domain
- name: Restart smbd
  become: true
  ansible.builtin.service:
    name: smbd
    state: restarted

- name: Restart nmbd
  become: true
  ansible.builtin.service:
    name: nmbd
    state: restarted

- name: Restart winbind
  become: true
  ansible.builtin.service:
    name: winbind
    state: restarted

- name: Restart sssd
  become: true
  ansible.builtin.service:
    name: sssd
    state: restarted
